name: Update IPTV List

on:
  schedule:
    - cron: '0 0 * * *'   # Svaki dan u ponoć
  workflow_dispatch:      # Omogućuje ručno pokretanje preko GitHub sučelja

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2 # POPRAVLJENO: Korištenje najnovije podverzije koja je prilagođena za novi Node.js
      
      - name: Make validator executable
        run: chmod +x update/validate.sh
      
      - name: Run validation
        run: ./update/validate.sh
      
      - name: Commit and push if changed
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@://github.com"
          git add playlists/main.m3u
          
          # Provjeri ima li stvarnih promjena u playlisti prije nego napraviš commit
          if ! git diff --staged --quiet; then
            git commit -m "Auto-update playlist $(date +'%Y-%m-%d %H:%M')"
            git push
          else
            echo "Nema promjena za commit."
          fi
